### ISSUE TITLE
Preservation of comments

### ISSUE THREAD

**Issue by levisl176** [sindresorhus/gulp-ruby-sass#190]
Would it be feasible to add an option for preserving comments from the original SASS code? Perhaps as a possible value for the `style` option?

**Comment by robwierzbowski** [comment]
You can preserve comments in your Sass by using standard CSS comments like so:

```scss
/* I will be in the output */
// I won't.
body { background: pink; }
```

If you're looking for something different I would ask on the Sass issue queue. In general we don't want to change anything that Sass does in this plugin.
