### ISSUE TITLE
Get a different random number within a SCSS for loop

### ISSUE THREAD

**Issue by MrTibbles** [sindresorhus/gulp-ruby-sass#237]
I am trying to generate a random number upon each iteration of a for loop in SCSS, however it simply returns the same number on DOM load for all elements targeted within the loop. Im pretty sure my syntax is correct, but clearly not!

Premise: I am building a brick wall and applying a different brick texture/image to each brick via the SCSS loop. I am attempting to apply a random background image for 16 elements with a potential of 6 background images to choose from. My SASS is version 3.4.14.

scss -v Sass 3.4.14 (Selective Steve)

```scss
@for $i from 1 through 6 {
  &.front:nth-child(#{$i}), &.back:nth-child(#{$i}) {
    $brick-bg: '../image/brick' + random(6) + '.jpg';
    background-image: url($brick-bg);
    background-size: 100% 100%;
  }
}
```
